### ISSUE TITLE
Fail to list VPCs due to invalid  json schema

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack-go#25]
Environment:

ACS: 4.16.0
OS: Ubuntu 21.10
SDK: v.2.12.0 

Issue:
SDK fails to unmarshall `listVPCs` result when there are network tiers attached to a VPC. Here's my output:
`VPCService_test.go:69: Failed to list VPCs due to: json: cannot unmarshal object into Go struct field VPC.vpc.network of type string`

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack-go/pull/26
