### ISSUE TITLE
CI/CD support

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack-go#27]
Discussion

It's a good time to add a CI/CD to this project. Which one to pick? Our options are
- gitlab
- github actions
- circle-ci
- travis
- teamcity
- etc

Should we vote before picking up one?

**Comment by synergiator** [comment]
agreed! in some GitHub projects, before GitHub Actions appeared, I had seen integrations with up to 3 CIs simultaneously, choices being those times Circle-CI, and Travis.

**Comment by rohityadavcloud** [comment]
Clsoing we've moved to Github actions now - any further enhancements, PRs are welcome.
