### ISSUE TITLE
DomainService Fails to Unmarshal DomainChildren

### ISSUE THREAD

**Issue by rejoshed** [apache/cloudstack-go#34]
Hello,

In using CS-Go, I noticed that listDomainChildren fails to unmarshal DomainChildren.

I modified the [JSON tag](https://github.com/apache/cloudstack-go/blob/c2b196979dc18c8b53d76ab16b6f26c7775e9836/cloudstack/DomainService.go#L579) and it worked perfectly.

``` Go
    DomainChildren []*DomainChildren `json:"domain"`
```

I don't know if this is an issue across all versions of the CloudStack API. I personally work against 4.16.

I'd be happy to PR a change, but again I'm not sure if it would be backward compatible with older API versions.

**Comment by rejoshed** [comment]
Also, should it be considered an error if unmarshalling fails? I sort of think so.

**Comment by davidjumani** [comment]
@rejoshed Can you please use the [v2.13.1](https://github.com/apache/cloudstack-go/releases/tag/v2.13.1) tag. The fix has been added
