### ISSUE TITLE
bug: async client don't  support timeout

### ISSUE THREAD

**Issue by tetra12** [apache/cloudstack-go#36]
I'm trying to set an `async timeout of 1 sec` with the following code:

```go
func MakeClient() *cloudstack.CloudStackClient {

       acsTimeout := 1 // sec

	cs := cloudstack.NewAsyncClient(apiURL, apiKey, secretKey, false)
	cs.AsyncTimeout(acsTimeout)

	return cs
}
```
However, when I run a test on the real infra, I'm getting this:
```bash
=== RUN   TestVPC_create
INFO[2022-05-25T18:36:01+03:00] Success                                      
--- PASS: TestVPC_create (3.38s)
```

So this test took `3.38 sec` without being timed out by the ACS client. I also look :eyes: into the impl and found out it to be rather poor.

Question: could anyone confirm the valid functionality of `async` client? Otherwise, I'm taking a lead to update the async part to match the expected functionality :roll_eyes:

**Comment by rohityadavcloud** [comment]
Closing this on @tetra12 's remarks at https://github.com/apache/cloudstack-go/pull/37#issuecomment-1779378444
`This refactor is NOT required, since current API implements both async and timeout`
