### ISSUE TITLE
Generate and tag against 4.15.2

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-go#8]
Hi @pdion891 I've updated the listApis.json using 4.15.2.0 with https://github.com/apache/cloudstack-go/commit/d6d45296f19abc1c72ee8d76b9da8a4a91f148b0. On running the generator it creates changes in `cloudstack/HostService.go` that overrides some of your manual changes:

```
cd generate
go build
./generate -api listApis.json
```

Can you do the above and see if you can address/fix your manual changes so either the generator is fixed or you simply use strings? (cloudstack/HostService.go)

**Comment by rhtyd** [comment]
ping @pdion891

**Comment by pdion891** [comment]
That's going to take some time to get resolved in generate.go, unless we just merge manual changes in`HostService.go`?

**Comment by rhtyd** [comment]
Should we merge the auto-generated changes for 4.15.2 @pdion891 I've pinged my colleague @Pearl1594 to see if generate.go can be fixed to do the changes (so manual changes are not required).
