### ISSUE TITLE
createUser/updateUser APIs need to be POST

### ISSUE THREAD

**Issue by mlsorensen** [apache/cloudstack-go#85]
https://github.com/apache/cloudstack-go/blob/0d335efa7425b204db7a8030522493f829fad6f0/generate/generate.go#L1701

The generation code uses post calls for a subset of APIs that are sensitive or large. Eventually the `listApis` should advertise which APIs these are, but until then we need to switch these `createUser` and `updateUser` calls (and any other that may send sensitive info) over to use POST.

**Comment by rohit-satya** [comment]
@mlsorensen Please assign this to me

**Comment by shwstppr** [comment]
@rohit-satya there is already a PR for this now, https://github.com/apache/cloudstack-go/pull/86. You may help review/test that

**Comment by phsm** [comment]
Perhaps this issue can be closed as the referenced PR has been merged.

**Comment by DaanHoogland** [comment]
fixed by #86
